Notes
* Dogfooding
** Ubuntu Gnome
Exit the default fcitx5 and then run
fcitx5 -d --verbose=*=5 or --verbose={categoryname}=5,{categoryname}=5

Use with care that category:keytrace will output my passwords inputting to browser etc to error logs.
On last resort, hook into imconfig's run im script /usr/share/im-config/data/??_fcitx5.rc or /usr/bin/fcitx5.

** Dictionary place
As a desktop app following the standard, data should better be loaded from subdir for this component only under XDG_DATA_HOME for personal dictionary and XDG_DATA_DIRS for static common dictionary.
Although, emacs + SKK users tend to share dictionary file among ddskk and IME so this might have to be fixed to be configurable in the future.

* Q
** How config works?
Create Option class.
Create a Configuration class.
Override setConfig, getConfig.
Set configurable on conf file.


** What is d_func and q_func in fcitx?
Keeping lib binary interface same, access all data via d_ptr.
Same reason, access all methods via q_ptr.
Probably same as Qt library.

** conf and addon.conf
What is Addon entry? name of lib? filename? fedora metainfo like name? What option is configurable here?
fcitx5/src/lib/fcitx/addoninfo.cpp's list is addon.conf


** metainfo
metainfo project group == Fcitx??
https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/ doesn't define what each field means.