name: Build
on: [ workflow_dispatch ]
jobs:
  Build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cskk_ver: [0.8.1]
    steps:
    # TODO: Fix to get latest release automatically?
    - name: Download & install libcskk
      run: |
        wget https://github.com/naokiri/cskk/releases/download/v${{ matrix.cskk_ver }}/libcskk_${{ matrix.cskk_ver }}_amd64.deb
        sudo apt-get install ./libcskk_${{ matrix.cskk_ver }}_amd64.deb
    - name: Install required libs and dependencies
      run: |
        sudo apt-get install extra-cmake-modules libfcitx5core-dev qtbase5-dev libfcitx5-qt-dev gettext
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: output some debug info
      run: |
        ls /usr/local/lib/
        ls /usr/local/lib/cskk
#    - name: Setup cmake
#      uses: jwlawson/actions-setup-cmake@v1.12
#    - name: build
#      run: |
#        mkdir build &&
#        cd build &&
#        cmake .. &&
#        make
    - name: Build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        cc: gcc
        cxx: c++
        build-type: Release
        run-test: false
        build-options: --verbose
    - name: Output cmakecache
      if: ${{ always() }}
      run: |
        ls &&
        cat /home/runner/work/fcitx5-cskk/build/CMakeCache.txt

      

