name: Build
on: [ workflow_dispatch ]
jobs:
  Build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cskk_ver: [0.8.1]
    steps:
    # TODO: Fix to get latest release automatically?
    - name: Download & install libcskk
      run: |
        wget https://github.com/naokiri/cskk/releases/download/v${{ matrix.cskk_ver }}/libcskk_${{ matrix.cskk_ver }}_amd64.deb
        sudo apt-get install ./libcskk_${{ matrix.cskk_ver }}_amd64.deb
    - name: Install required libs
      run: |
        sudo apt-get install extra-cmake-modules libfcitx5core-dev qtbase5-dev
    - name: checkout
      uses: actions/checkout@v3
    - name: Build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        cc: gcc
        cxx: g++
        build-type: Release
        run-test: false

