name: Release x86_64 deb artifact on release published
on:
  release:
    types:
      - published

jobs:
  Build:
    runs-on: ubuntu-24.04
#    strategy:
#      matrix:
#        cskk_ver: [0.8.1]
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: check fcitx5-cskk version
      id: version
      run: |
        echo version=`bin/version.sh` >> ${GITHUB_OUTPUT}
    - name: check cskk version
      id: cskk_version
      run: |
        echo cskk_version=`bin/cskk_version.sh` >> ${GITHUB_OUTPUT}
    - name: check fcitx5-cskk version exists in metainfo
      run: |
        bin/metainfo_version.sh
    - name: Check release tag matches version
      run: test "refs/tags/v${{ steps.version.outputs.version }}" = ${{ github.ref }}
    - name: Install required build environment
      uses: ./.github/actions/archlinux_build_environment_setup
    - name: Build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        cc: gcc
        cxx: c++
        build-type: Release
        run-test: false
        configure-options: -DFCITX_INSTALL_USE_FCITX_SYS_PATHS=ON
        build-options: --verbose
    - name: Pack deb
      run: |
        cd ${{ runner.workspace }}/build
        cpack -G DEB -DFCITX_INSTALL_USE_FCITX_SYS_PATHS=On
    - name: Attatch artifact to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ runner.workspace }}/fcitx5-cskk/_packages/fcitx5-cskk_${{ steps.version.outputs.version }}_amd64.deb